eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Service Discovery (Eureka) ni yoqish

      routes:
        - id: student-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**   # Student service uchun marshrut

        - id: school-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**    # School service uchun marshrut
management:
  tracing:
    sampling:
      probability: 1.0